image_gallery_app/core/urls.py
from django.urls import path
from image_gallery_app.core.views import home, upload_image, like

urlpatterns = [
    path('', home, name='home'),
    path('upload_image/', upload_image, name='upload_image'),
    path('like/<int:id>/', like, name='like'),
]

image_gallery_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('image_gallery_app.core.urls')),
    path('admin/', admin.site.urls),
    
]

image_gallery_app/core/models.py
from django.db import models
from django.db.models import F


class ImageGallery(models.Model):
    UPLOADED = 'up'
    APPROVED = 'ok'
    STATUS_CHOICES = (
        (UPLOADED, 'uploaded'),
        (APPROVED, 'approved'),
    )
    image = models.ImageField(upload_to='weeding_images/')
    title = models.CharField(max_length=20, blank=True)
    likes = models.IntegerField(default=0)
    uploaded_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=2,
                              choices=STATUS_CHOICES,
                              default=UPLOADED)

    class Meta:
        ordering = ['uploaded_at', 'likes']

    def __str__(self):
        return self.title

    def increse_likes(self):
        self.likes = F('likes') + 1
        self.save()
        self.refresh_from_db()

image_gallery_app/core/forms.py
from django import forms
from image_gallery_app.core.models import ImageGallery


class UploadImageForm(forms.ModelForm):
    class Meta:
        model = ImageGallery
        fields = ('image', 'title')

image_gallery_app/core/views.py
from django.views.generic import ListView
from django.views.generic.edit import CreateView
from django.views import View
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from image_gallery_app.core.forms import UploadImageForm
from image_gallery_app.core.models import ImageGallery


class ImagesListView(ListView):
    model = ImageGallery
    filter_fields = ('uploaded_at', 'likes')
    template_name = 'home.html'
    paginate_by = 5

    def get_queryset(self):
        query_string = self.request.GET.get('sort_by')
        if query_string in self.filter_fields:
            return self.model.objects.filter(status='ok').order_by(f'-{query_string}')
        return self.model.objects.filter(status='ok')


class LikeView(View):

    def post(self, request, *args, **kwargs):
        if not self.request.is_ajax():
            error = dict(error='Request is not AJAX.')
            return JsonResponse(error, status=400)

        image_id = kwargs['id']
        image = get_object_or_404(ImageGallery, pk=image_id)
        image.increse_likes()
        return JsonResponse({'likes': image.likes})


like = LikeView.as_view()
upload_image = CreateView.as_view(template_name='upload_image.html',
                                  form_class=UploadImageForm,
                                  success_url='/')
home = ImagesListView.as_view()

image_gallery_app/core/templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>

    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
        {% include 'nav.html' only %}
        {% block content %}
        {% endblock %}

    <!--JavaScript at end of body for optimized loading-->
    <script type="text/javascript" src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/app.js' %}"></script>
  </body>
</html>

image_gallery_app/core/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="container center">
    <div class="row">
            <div class="col s12 center">
                <h3> Weeding friends gallery</h3>
                {% include "image_gallery.html" with images=imagegallery_list %} 
            </div>
    </div>
</div>

{% endblock %}

image_gallery_app/core/templates/image_gallery.html
<div class="row">
    <div class="class col s2 m2 l2">
        <form action="{% url 'home' %}" method="get">
            <select class="browser-default", name="sort_by">
                <option value="" disabled selected>Sort by</option>
                <option value="uploaded_at">date</option>
                <option value="likes">like</option>
            </select>
            <input type="submit"/>
        </form>
    </div>
</div>

<div class="row">
    {% for image in images %}
    <div class="col s4 m4 l4">
        <div class="card">
          <div class="card-image">
              <img src="{{ image.image.url }}">
              <span class="card-title"></span>
          </div>
          <div class="card-content">
                <p><strong>Title:</strong> {{ image.title }}</p>
          </div>
          <div class="card-action">
                <a href="javascript:void(0)" class="like" data-image-id="{{ image.id }}" >Like ({{ image.likes}})</a>
          </div>
        </div>
    </div>
    {% empty %}
    <h4> Not images yet!</h4>
    {% endfor %}
</div>

image_gallery_app/core/templates/nav.html
<nav>
    <div class="nav-wrapper teal lighten-2">
      <!-- <a href="#" class="brand-logo right">Logo</a> -->
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="left hide-on-med-and-down">
        <li><a href="{% url 'upload_image' %}">Upload Image</a></li>
        <li><a href="{% url 'home' %}">Image Gallery</a></li>
        <li><a href="{% url 'admin:index' %}">Login</a></li>
      </ul>
    </div>
</nav>
<ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'upload_image' %}">Upload Image</a></li>
    <li><a href="{% url 'home' %}">Image Gallery</a></li>
</ul>

image_gallery_app/core/templates/upload_image.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
        <div class="col s12 center">
            <h3>Upload Image</h3>
        </div>
</div>
<div class="row">
    <div class="col s4 offset-s4 center">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% if form.image.errors %}
                {% for error in form.image.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
            {% endif %}
            <div class="input-field">
                <input id="input_text" type="text" data-length="10" name="title">
                <label for="input_text">Title</label>
            </div>
            <div class="file-field input-field">
                <div class="btn">
                    <span>Image</span>
                    <input type="file" name="image">
                </div>
                <div class="file-path-wrapper">
                    <input class="file-path validate" type="text" name="image" placeholder="Click here to upload">
                </div>
            </div>
            <button class="btn waves-effect waves-light center" type="submit" name="action">Upload
            </button>
        </form>
        <p><a href="{% url 'home' %}">Return to Image Gallery</a></p>
    </div>
</div>
{% endblock %}